# -*- coding: utf-8 -*-
"""software_lab_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MWPpJqzqyDHU0JmBeJ_T85Lk1k9iYmtg
"""

import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as mpl
df= pd.read_excel("datadisciplinary.xlsx")
print(df)

data = np.random.randint(0, 100, size=df.shape[0])  # Use df.shape[0] to match rows

# Create a new DataFrame with one column
df_list = pd.DataFrame(data, columns=['DISCIPLINARYGRADE'])

# Print the new DataFrame
print(df_list)

df.DISCIPLINARYGRADE=df_list.DISCIPLINARYGRADE
print(df)

mean_by_semester = df.groupby('SEMESTER')['DISCIPLINARYGRADE'].mean()

# Print the result
print(mean_by_semester)

median_by_semester = df.groupby('SEMESTER')['DISCIPLINARYGRADE'].median()

# Print the result
print(median_by_semester)

mode_by_semester = df.groupby('SEMESTER')['DISCIPLINARYGRADE'].agg(lambda x: x.mode()[0] if not x.mode().empty else np.nan)

# Print the result
print(mode_by_semester)

#BRANCHCODE
mean_by_branch = df.groupby('BRANCHCODE')['DISCIPLINARYGRADE'].mean()

# Print the result
print(mean_by_semester)

#BRANCHCODE
median_by_branch= df.groupby('BRANCHCODE')['DISCIPLINARYGRADE'].median()

# Print the result
print(median_by_semester)

mode_by_branch = df.groupby('BRANCHCODE')['DISCIPLINARYGRADE'].agg(lambda x: x.mode()[0] if not x.mode().empty else np.nan)

# Print the result
print(mode_by_branch)

std_by_semester = df.groupby('SEMESTER')['DISCIPLINARYGRADE'].std()

# Print the result
print(std_by_semester)

std_by_branch = df.groupby('BRANCHCODE')['DISCIPLINARYGRADE'].std()

# Print the result
print(std_by_branch)

variance_by_semester = df.groupby('SEMESTER')['DISCIPLINARYGRADE'].var()

# Print the result
print(variance_by_semester)

variance_by_branch = df.groupby('BRANCHCODE')['DISCIPLINARYGRADE'].var()

# Print the result
print(variance_by_branch)